version: "3.9"

services:
  nobita:
    build: .
    container_name: nobita_bot
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - "9091:9091"   # 👈 custom port (no 8080)
    environment:
      - DATABASE_URL=postgresql://nobita:strongpass@postgres:5544/nobita_db

  postgres:
    image: postgres:15
    container_name: nobita_postgres
    restart: always
    environment:
      POSTGRES_USER: nobita
      POSTGRES_PASSWORD: strongpass
      POSTGRES_DB: nobita_db
    command: -p 5544   # 👈 postgres internal port bhi change
    ports:
      - "5544:5544"    # 👈 no 5432 anywhere
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
